model: Bifrost:mistral/labs-devstral-small-2512
clients:
  - type: openai-compatible
    name: Bifrost
    api_base: http://bifrost.orb.local/openai/v1
    models:
      - name: mistral/codestral-latest
      - name: mistral/devstral-2512
      - name: mistral/labs-devstral-small-2512
      - name: mistral/ministral-14b-latest
      - name: mistral/mistral-large-latest
      - name: nvidia/minimaxai/minimax-m2.1
      - name: nvidia/moonshotai/kimi-k2.5
      - name: nvidia/nvidia/nemotron-3-nano-30b-a3b
      - name: nvidia/openai/gpt-oss-120b
      - name: nvidia/openai/gpt-oss-20b
      - name: nvidia/stepfun-ai/step-3.5-flash
      - name: nvidia/z-ai/glm4.7
      - name: opencode/big-pickle
      - name: opencode/glm-4.7-free
      - name: opencode/gpt-5-nano
      - name: opencode/kimi-k2.5-free
      - name: opencode/minimax-m2.1-free
