[default_session]
preview_command = "eza --group-directories-first --icons --all --git --color=always -lh {}"

[[session]]
name = "config"
path = "~/.config"

[[session]]
name = "chezmoi"
path = "~/.local/share/chezmoi"
startup_command = "lazygit"

[[session]]
name = "downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "spotify"
path = "~/.config/spotify-player"
startup_command = "spotify_player"

[[window]]
name = "vim"
startup_script = "vim"

[[window]]
name = "lazygit"
startup_script = "lazygit"
