[tools]
amp = "latest"
bun = "latest"
gemini = "latest"
node = "lts"
opencode = "latest"
python = "3.12"
rust = "latest"
uv = "latest"
"npm:@qwen-code/qwen-code" = "latest"
"pipx:llm" = { version = "latest", uvx_args = "--with llm-cmd-git,llm-mistral,llm-ollama" }

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
npm.bun = true
pipx.uvx = true
python.uv_venv_auto = true
